const products = [
  {
    _id: 1,
    name: 'Chocolate Drip Var01',
    image: '/images/choco1.png',
    description:'Chocolate Drip Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 689.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: 2,
    name: 'Chocolate Drip Var02',
    image: '/images/choco2.png',
    description:'Chocomoist Themed Cakes',
    brand: 'Local',
    category: 'Cakes',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: 3,
    name: 'Chocolate Drip Var03',
    image: '/images/choco3.png',
    description:'Cartoon/Character Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 629.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: 4,
    name: 'Chocolate Drip Var05',
    image: '/images/character1.png',
    description:'Cartoon/Character Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 699.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: 5,
    name: 'Chocolate Drip Var06',
    image: '/images/choco4.png',
    description:'Cartoon/Character Cakes',
    brand: 'Local',
    category: 'Cakes',
    price: 649.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: 6,
    name: 'Chocolate Drip Var07',
    image: '/images/choco5.png',
    description:'Number Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
{
    _id: 7,
    name: 'Chocolate Drip Var08',
    image: '/images/choco6.png',
    description:'Chocolate Drip Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
{
    _id: 8,
    name: 'Chocolate Drip Var08',
    image: '/images/choco7.png',
    description:'Chocomoist Themed Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 729.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: 9,
    name: 'Chocolate Drip Var01',
    image: '/images/choco11.png',
    description:'Chocolate Drip Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 889.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: 10,
    name: 'Chocolate Drip Var02',
    image: '/images/choco12.png',
    description:'Chocomoist Themed Cakes',
    brand: 'Local',
    category: 'Cakes',
    price: 799.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: 11,
    name: 'Chocolate Drip Var03',
    image: '/images/choco3.png',
    description:'Cartoon/Character Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 629.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: 12,
    name: 'Chocolate Drip Var05',
    image: '/images/choco4.png',
    description:'Cartoon/Character Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 799.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: 13,
    name: 'Chocolate Drip Var06',
    image: '/images/choco4.png',
    description:'Cartoon/Character Cakes',
    brand: 'Local',
    category: 'Cakes',
    price: 649.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: 14,
    name: 'Chocolate Drip Var07',
    image: '/images/choco5.png',
    description:'Number Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 829.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
{
    _id: 15,
    name: 'Chocolate Drip Var08',
    image: '/images/character1.png',
    description:'Chocolate Drip Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 829.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
{
    _id:16,
    name: 'Chocolate Drip Var08',
    image: '/images/choco6.png',
    description:'Chocomoist Themed Cakes',
    brand: 'Local',
    category: 'Pastry',
    price: 829.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]
export default products
